### PR TITLE
Hide ManageIQ Password in Ansible log

### PR DESCRIPTION
**Pull request by dkorn**

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @enoodle @ivanhorvath please review

**Comment by enoodle** [comment]
@dkorn this is only for passwords through environment variables? Because I don't see them in the logs when supplying them from the playbook.

**Comment by dkorn** [comment]
> @dkorn this is only for passwords through environment variables? Because I don't see them in the logs when supplying them from the playbook.

it is for all password parameters, not just environment variables. for example `provider_api_auth_token` in `manageiq_provider` module

you can see them in the general ansible log or if you run tasks using `with_items`

**Comment by cben** [comment]
LGTM

**Pull request merged**
