### PR TITLE
Add SSL Cert Verification support

### PR DESCRIPTION
**Pull request by dkorn**
SSL certificate verification is enabled by default.
To use a self-signed certificate pass the certificate file or directory path using the ca_bundle_path option: `ca_bundle_path: '/path/to/certfile'`.

To ignore verifying the SSL certificate pass `verify_ssl: False`

depends on: https://github.com/ManageIQ/manageiq-api-client-python/pull/10

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @simon3z @enoodle @twiest @kwoodson please review

**Review by cben — APPROVED** [review]
Generally LGTM except it might be unclear what connection this refers to (ansible to MIQ, not MIQ to provider, right?)

**Comment by dkorn** [comment]
> Generally LGTM except it might be unclear what connection this refers to (ansible to MIQ, not MIQ to provider, right?)

@cben right, ansible to MIQ env. If you have a suggestion on how to make it clearer please propose it.

**Comment by twiest** [comment]
The ssl changes look good.

For posterity, as we've discussed before, I still dislike `type: 'openshift-enterprise'`.

**Comment by dkorn** [comment]
> For posterity, as we've discussed before, I still dislike type: 'openshift-enterprise'.

@twiest there's a separate PR that handles the provider type issue https://github.com/dkorn/manageiq-ansible-module/pull/25, still need to change it according to what we've agreed - using the `provider_type` option which will match the types in the ManageIQ API [docs](http://manageiq.org/docs/reference/latest/api/reference/providers). 
As for the other options, as a short term solution, we will support the dedicated amazon and openshift options and will make the changes in the manageiq API to improve user experience.

**Comment by jarovo** [comment]
Could you add 4bf64289790 please?

**Comment by dkorn** [comment]
thanks @jaryn! added your commit.
merging.

**Pull request merged**
