### PR TITLE
Refactor: rename ManageIQ class to ManageIQProvider in manageiq_provider module

### PR DESCRIPTION
**Pull request by dkorn**

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @enoodle please review

**Review by enoodle — APPROVED** [review]
LGTM

**Comment by dkorn** [comment]
@cben any reason not to merge?

**Review by cben — APPROVED** [review]
No reason :)

**Comment by dkorn** [comment]
> No reason :)

Thanks :)

**Pull request merged**
