### PR TITLE
Fix endpoint authentication method bug

### PR DESCRIPTION
**Pull request by dkorn**
When passing a provider endpoind to manageiq API its authentication will only save if it includes userid and password or token, but not both (exclusive or).
This behavior is quite unpredictable, as one would expect and error or message when passing both options.

This change separates the generation of openshift provider endpoint from the amazon provider endpoint, thus making sure only one auth method is used for the provider's endpoint.

### CODE REVIEW

**Comment by dkorn** [comment]
@cben @enoodle please review

**Review by cben — APPROVED** [review]
Can you also add `assert_called_...` to at least one of the amazon tests, checking what we send?

For the record, the code in ManageIQ that made it fail when we also passed `username: null` are:
https://github.com/ManageIQ/manageiq/blob/ebb30f4ad663b4d6f78c5c6bd5d6761c6f73458b/app/models/mixins/authentication_mixin.rb#L134-L136
(`current[:new]` is left unset, exiting on `next if current[:old] == current[:new]` a few lines below)

We'll followup on ManageIQ side to either successfully tolerate extra auth fields with null value, or return an error.

**Comment by dkorn** [comment]
> Can you also add assert_called_... to at least one of the amazon tests, checking what we send?

Done, thanks

**Comment by cben** [comment]
:+1:

**Pull request merged**
