### PR TITLE
Fix NameError in manageiq_tag_assignment module

### PR DESCRIPTION
**Pull request by cben**
There is no such var `entity` currently in the code.
This exception is obscuring other errors.

@pavelzag Please review

### CODE REVIEW

**Comment by pavelzag** [comment]
I ran the yml successfully but can't see the change in the GUI

**Comment by cben** [comment]
Can you review the code change here?  I'd like to merge this.

Providers GUI has 3 views (tiny icons near top right): dashboard **details** topology
"details" view contains "Smart Management" which for me does show the assigned tag:
manageiq containers providers

**Comment by cben** [comment]
@zgalor or @enoodle tiny fix please review

**Review by zgalor — APPROVED** [review]
:+1: LGTM

**Pull request merged**
